version: '3.9'
services:
  client:
    container_name: nextjs-client
    build: .
    image: nextjs-client
    ports:
      - "3000:3000"
    volumes:
      - clientvol:/clientdata
volumes:
  clientvol:
    name: clientvol